name: DansSpawnSystem
version: '${project.version}'
author: DanTheTechMan
main: dansplugins.spawnsystem.DansSpawnSystem
api-version: 1.13

commands:
  resetspawn:

permissions:
  spawnsystem.reset.self:
    default: op
  spawnsystem.reset.others:
    default: op
  spawnsystem.placeSpawnSign:
    default: op
  spawnsystem.breakSpawnSign:
    default: op
  spawnsystem.admin:
    default: op