name: DansSpawnSystem
version: 1.1-alpha-1
author: DanTheTechMan
main: dansplugins.spawnsystem.DansSpawnSystem
api-version: 1.13

commands:
  resetspawn:

permissions:
  dansplugins.spawnsystem.reset.self:
    default: op
  dansplugins.spawnsystem.reset.others:
    default: op
  dansplugins.placeSpawnSign:
    default: op
  dansplugins.breakSpawnSign:
    default: op